from tkinter import *
root = Tk()
lbl1 = Label(root,text='Username: ')
lbl2 = Label(root,text='Password: ')
txtbox1 = Entry(root)
txtbox2 = Entry(root)
lbl1.grid(row = 0)
lbl2.grid(row = 1)
txtbox1.grid(row = 0,column = 1)
txtbox2.grid(row = 1,column = 1)
c = Checkbutton(root,text='Keep me logged in')
c.grid(columnspan=2)
btn = Button(root,text='Login')
btn.grid(row = 3,columnspan=2)
root.mainloop()
